Move
beehoney221/OOO pull request #1
Opened 2023-12-08 12:15 UTC by matvey-put

2023-12-08 12:22 UTC, matvey-put reviewed
Принято.
Поправить:
1. Пустые строчки в конце
2. Warning'и в векторе и тестах.

2023-12-22 10:50 UTC, zaryanezrya requested changes

2023-12-22 10:50 UTC, zaryanezrya commented on .github/workflows/main.yml
Пустая строка?

2023-12-22 10:50 UTC, zaryanezrya commented on SpaceBattle.Lib/Vector.cs
> +            for (var i = 0; i < array_1._dimension; i++)
LINQ

2023-12-22 10:50 UTC, zaryanezrya commented on SpaceBattle.Lib/Vector.cs
> +        if (array_1._dimension == array_2._dimension)
if (array_1._dimension != array_2._dimension) {
  throw new Exception();
}

2023-12-22 11:04 UTC, zaryanezrya requested changes

2023-12-22 11:04 UTC, zaryanezrya commented on .github/workflows/main.yml
> +  push:
pull_request:

2023-12-22 12:27 UTC, zaryanezrya approved these changes

2023-12-24 16:44 UTC, merged